applicationName: slackpay
slack_token: 
  <team_domain> : <slack_api_access_token>
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
