applicationName: slackpay
slack_token: xoxp-2801095921-2806004971-4743837401-be17e8
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
